<html>
<?php echo $this->doctype("XHTML1_TRANSITIONAL"), PHP_EOL; ?>

<meta charset="UTF-8" />
<?php echo $this->headTitle('SIMENS ' . $this->translate('Systeme Information Medical'))->setSeparator(' - ')->setAutoEscape(false) ?>

<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<?php

echo $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
echo $this->headLink()->prependStylesheet($this->basePath() . '/css/jquery.contextMenu.css');
echo $this->headLink()->prependStylesheet($this->basePath() . '/css/matrix-style-cons.css');
echo $this->headLink()->prependStylesheet($this->basePath() . '/css/matrix-media.css');
echo $this->headLink()->prependStylesheet($this->basePath() . '/js/w2ui/w2ui-1.4.3.min.css');
echo $this->headLink()->prependStylesheet($this->basePath() . '/css/menu-sidenav.css');
echo $this->headLink()->prependStylesheet($this->basePath() . '/css/editor-menugauche.scss');


echo $this->headLink()->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.css');
//echo $this->headLink()->prependStylesheet($this->basePath().'/font-awesome-4.7.0/css/font-awesome.css');
echo $this->headLink()->prependStylesheet($this->basePath() . '/font-awesome-5.15.3/css/all.css');



$this->headScript()->appendFile($this->basePath() . '/js/jquery.min.js');
$this->headScript()->appendFile($this->basePath() . '/js/matrix.js');

echo $this->headTitle($this->pageTitle); ?>
<?php
echo $this->headLink()->appendStylesheet($this->basePath() . '/css/smoothness/jquery-ui.css');
echo $this->headLink()->appendStylesheet($this->basePath() . '/js/plugins/multiselect/css/multi-select.css');
?>

<?php $this->headScript()->appendFile($this->basePath() . '/js/jquery-1.9.1.js');
$this->headScript()->appendFile($this->basePath() . '/js/jquery-ui.js');
$this->headScript()->appendFile($this->basePath() . '/js/jquery.dataTables.min.js');
$this->headScript()->appendFile($this->basePath() . '/js/plugins/contextMenu/bootstrap-contextmenu.js');

$this->headScript()->appendFile($this->basePath() . '/js/jquery.maskedinput.js');
$this->headScript()->appendFile($this->basePath() . '/js/controle_saisie/controle_saisie.js');

$this->headScript()->appendFile($this->basePath() . '/js/plugins/multiselect/js/jquery.multi-select.js');
$this->headScript()->appendFile($this->basePath() . '/js/plugins/multiselect/js/jquery.quicksearch.js');

$this->headScript()->appendFile($this->basePath() . '/js/w2ui/w2ui-1.4.3.min.js');

//$this->headScript()->appendFile($this->basePath().'/js/bootstrap.min.js');
?>

<?php echo $this->headScript(); ?>

<head>
</head>


<?php

//RECUPERER LES INFOS SUR LE MEDECIN OU SUR LE SURVEILLANT
$user = $this->layout()->user;
$nom = $user['Nom'];
$prenom = $user['Prenom'];
$service = $this->layout()->service;
if ($user['role'] == 'superAdmin') {
  $service = "INFORMATIQUE";
}

$sexe = $user['Sexe'];
$civilite =  'Mme';
$photo = "User.png";

if ($sexe == 'Masculin') {
  $civilite = 'M';
}

if ($sexe == 'Féminin') {
  $photo = 'UserFemale1.jpg';
}

?>


<body id="corps-page">


  <table style="width: 100%; height: 100%; background: white;">

    <tr style="width: 100%;">
      <!-- MENU GAUCHE -->
      <td id="menu-geuche-page" style="width: 16%; background: gree;">
        <!-- ENTETE -->
        <div style="position: fixed; top:0px; background: re; width:100%; height: 10%; ">
          <div id="logo-simens-style">
            SIMENS<sup>+</sup></div>
        </div>

        <!-- CORPS -->
        <div style="position: relative;  width:100%; height: 70%;  background: yello;">

          <ul class="accordion-menu" style="display:none;">

            <!-- MENU PROFIL SECRETARIAT -->
            <!-- MENU PROFIL SECRETARIAT -->

            <li class="profil-secretariat-menu" id="profil-secretariat-menu-rubrique-dossier-patient">
              <div class="dropdownlink">
                <i class="icon-folder-close"></i>
                Dossier patient
                <i class="icon-chevron-down" aria-hidden="true"></i>
              </div>

              <ul class="submenuItems">
                <li><a id="nouveau-patient-select" href="<?php echo $this->url('secretariat', array('action' => 'ajouter-patient')); ?>"><i class="fa fa-angle-right"></i> Nouveau</a></li>
                <li><a id="liste-patient-select" href="<?php echo $this->basePath() . "/secretariat/liste-patient"; ?>"><i class="fa fa-angle-right"></i> Liste</a></li>
              </ul>
            </li>

            <li class="profil-secretariat-menu" id="profil-secretariat-menu-rubrique-admission">
              <div class="dropdownlink">
                <i class="icon-home" aria-hidden="true"></i>
                Admission
                <i class="icon-chevron-down" aria-hidden="true"></i>
              </div>
              <ul class="submenuItems">
                <li><a id="dossier-patient-select" href="<?php echo $this->basePath() . "/secretariat/admission"; ?>"><i class="fa fa-angle-right"></i> Dossier patient</a></li>
                <li><a id="patient-admis-select" href="<?php echo $this->basePath() . "/secretariat/liste-patients-admis"; ?>"><i class="fa fa-angle-right"></i> Liste des admis</a></li>
              </ul>
            </li>

            <li class="profil-secretariat-menu" id="profil-secretariat-menu-rubrique-rendez-vous">
              <div class="dropdownlink">
                <i class="icon-home" aria-hidden="true"></i>
                Rendez-vous
                <i class="icon-chevron-down" aria-hidden="true"></i>
              </div>
              <ul class="submenuItems">
                <li><a id="fixer-rendez-vous-select" href="<?php echo $this->basePath() . "/secretariat/fixer-rendez-vous"; ?>"><i class="fa fa-angle-right"></i> Fixer RV</a></li>
                <li><a id="programmer-rendez-vous-select" href="<?php echo $this->basePath() . "/secretariat/programmer-rendez-vous"; ?>"><i class="fa fa-angle-right"></i> Programmer RV</a></li>
                <li><a id="liste-rendez-vous-select" href="<?php echo $this->basePath() . "/secretariat/liste-rendez-vous"; ?>"><i class="fa fa-angle-right"></i> Liste des rendez-vous</a></li>

              </ul>
            </li>

            <!-- MENU PROFIL MEDECIN -->
            <!-- MENU PROFIL MEDECIN -->

            <li class="profil-medecin-menu" id="profil-medecin-menu-rubrique-consultations">
              <div class="dropdownlink">
                <i class="icon-home" aria-hidden="true"></i>
                Consultations
                <i class="icon-chevron-down" aria-hidden="true"></i>
              </div>
              <ul class="submenuItems">
                <li><a id="consultation-encours-select" href="<?php echo $this->url('orl', array('action' => 'liste-consultation')); ?>"><i class="fa fa-angle-right"></i> En cours ...</a></li>
                <li><a id="patients-consultes-select" href="<?php echo $this->url('orl', array('action' => 'espace-recherche-med')); ?>"><i class="fa fa-angle-right"></i> Recherche</a></li>
              </ul>
            </li>

            <li class="profil-medecin-menu" id="profil-medecin-menu-rubrique-bloc">
              <div class="dropdownlink">
                <i class="icon-home" aria-hidden="true"></i>
                Bloc op&eacute;ratoire
                <i class="icon-chevron-down" aria-hidden="true"></i>
              </div>
              <ul class="submenuItems">
                <li><a id="protocole-operatoire-select" href="<?php echo $this->basePath() . "/orl/protocole-operatoire"; ?>"><i class="fa fa-angle-right"></i> C.R.O</a></li>
                <li><a id="liste-protocole-operatoire-select" href="<?php echo $this->basePath() . "/orl/liste-protocole-operatoire"; ?>"><i class="fa fa-angle-right"></i> Liste</a></li>
              </ul>
            </li>


          </ul>

          <!-- MENU *** AFFICHAGE - TABLEAU STATISTIQUE *** infirmerie -->
          <!-- <div class="menu-infos-urgences" style="position:relative; right: 0px; float: left; height: 20px; display: none; top: 30px;">

            <a class='btn-sm btn btn-warning' style="margin-left: 15px;" title="Infos sur les actes et examens"><i onclick="affichagePatientsActesExamens();" class="fa fa-info-circle" style="cursor: pointer; color: white; font-size: 20px;"></i> </a>
            <a class='btn-sm btn btn-success' style="margin-left: 0px;" title="R&eacute;gistre &agrave; imprimer"><i onclick="imprimerRegistreDesPatientsAdmis();" class="fa fa-registered" style="cursor: pointer; color: white; font-size: 20px;"></i> </a>

          </div> -->


        </div>

        <!-- PIED DE PAGE -->
        <text style="position: fixed; top: 95%; height: 70%; left: 30px; font-size: 12px;">
          &copy; 2022 - <a href='http://www.ugb.sn' style='color: black; text-decoration: none; font-family: times new roman;' target='_blank' ;> SIMENS </a>
        </text>
      </td>

      <!-- CONTENU -->
      <td style="width: 84%; background: yello;">
        <!-- ENTETE -->
        <div id="entete-bande-style">

          <img id="icon-user-param" onclick="getMenuDeroulant();" style="box-shadow: 10 10px 20px rgba(1, 0, 0, 0.5); cursor:pointer; float: right; position:relative; right: 50px; top: 12px; width: 40px; height: 40px; border-radius: 15%; background: white;" src="<?php echo $this->basePath() . '/images_icons/' . $photo; ?>" />

          <div style="position:relative; right: 60px; float: right; height: 20px; width: 230px; top: 13px; text-align: right; ">

            <span style="font-size: 17px; color: white; font-weight: bold; font-family: Times  New Roman;"><?php echo $prenom . ' ' . $nom; ?></span>


            <div style="width: 100%; padding-top: 2px; font-size: 13px; color: white; font-weight: bold; font-family: Times  New Roman;">

              <?php if ($user['role'] == 'medecin') { ?>

                <?php
                $baseUrl = $_SERVER['REQUEST_URI'];
                $tabURI  = explode('secretariat', $baseUrl);
                if (count($tabURI) == 2) {
                ?>
                  <a href='<?php echo $this->url('orl', array('action' => 'liste-consultation'));
                            ?>' style='text-decoration: none; color: white;' title='Consultation'>
                    <i class='icon-circle-arrow-left' style='font-size: 15px;'></i> &nbsp; | &nbsp;
                  </a>

                <?php } else { ?>
                  <a href='<?php echo $this->url('secretariat', array('action' => 'ajouter-patient'));
                            ?>' style='text-decoration: none; color: white;' title='Secretariat'>
                    <i class='icon-circle-arrow-right' style='font-size: 15px;'></i> &nbsp; | &nbsp;
                  </a>
                <?php } ?>

              <?php } ?>


              <?php if ($user['role'] == 'infirmier-service') { ?>
                <span> Infirmier de service</span>
              <?php } else if ($user['role'] == 'infirmier-tri') { ?>
                <span> Infirmier de tri</span>
              <?php } else if ($user['role'] == 'medecin') { ?>
                <span> M&eacute;decin</span>
              <?php } ?>

            </div>

          </div>




        </div>

        <!-- CORPS -->
        <div id="corpsContent" style="width: 100%; height: 100%; background: white;">
          <div id="corpsContentInterface">
            <?php echo $this->content; ?>
          </div>
        </div>

      </td>
    </tr>

  </table>


</body>

</html>

<style>
  .ui-tooltip {
    padding: 8px;
    position: absolute;
    z-index: 9999;
    max-width: 300px;
    -webkit-box-shadow: 0 0 5px #aaa;
    box-shadow: 0 0 5px #aaa;
  }

  body .ui-tooltip {
    border-width: 2px;
  }

  #corpsContent {
    overflow-y: scroll;
  }

  #corpsContentInterface {
    padding: 20px;
    padding-top: 85px;
  }

  .profil-secretariat-menu,
  .profil-medecin-menu,
  .profil-major-menu {
    display: none;
  }
















  /*
	  NEW CODE JUILLET 2021
  */


  input[type="text"],
  select,
  input[type="number"],
  textarea,
  input[type="email"],
  input[type="date"] {
    border: 2px solid rgba(23, 231, 186, 0.8);
    font-family: Poppins-Medium;
    font-size: 19px;
    line-height: 1.5;
    color: #666666;

    min-width: 20%;
    background: #fcfafa;
    border-radius: 15px;
  }

  input[type="date"] {
    height: 35px;
  }

  textarea {
    height: 50px;
    width: 90%
  }

  .style-operateur-input select {
    width: 90%;
    height: 35px;
  }

  label {
    color: black;

    font-size: 15px;

    font-family: cursive;

    margin-bottom: 7px;

    margin-left: 5px;

  }

  input[type="text"]:focus,
  input[type="email"]:focus,
  input[type="number"]:focus,
  input[type="date"]:focus,
  select:focus,
  textarea:focus {
    -webkit-animation: anim-shadow 0.3s ease-in-out forwards;
    animation: anim-shadow 0.3s ease-in-out forwards;
  }


  @-webkit-keyframes anim-shadow {
    to {
      box-shadow: 0px 0px 40px 5px rgba(23, 231, 186, 0.8);
      border: 2px solid rgba(23, 231, 186, 0.8);
    }
  }

  @keyframes anim-shadow {
    to {
      border: 2px solid rgba(23, 231, 186, 0.8);
      box-shadow: 0px 0px 15px 5px rgba(23, 231, 186, 0.8);
    }
  }

  .wrap-input100 {
    position: relative;
    z-index: 1;
  }
</style>






<script>
  var base_url = window.location.toString();
  var tabUrl = base_url.split("public");

  function modifierPassword() {

    var role = "<?php echo $user['role']; ?>";
    var id = 0;
    if (role == 'medecin') {
      id = 1;
    }
    if (role == 'infirmier-tri') {
      id = 2;
    }
    if (role == 'infirmier-service') {
      id = 3;
    }

    vart = tabUrl[0] + 'public/admin/modifier-password/' + id;
    $(location).attr("href", vart);
  }









  $(function() {
    var Accordion = function(el, multiple) {
      this.el = el || {};
      // more then one submenu open?
      this.multiple = multiple || false;

      var dropdownlink = this.el.find('.dropdownlink');
      dropdownlink.on('click', {
        el: this.el,
        multiple: this.multiple
      }, this.dropdown);

      dropdownlink.on('dblclick', {
        el2: this.el2,
        multiple: this.multiple,
      }, this.dropdown2);
    };

    //ANIMATION
    Accordion.prototype.dropdown = function(e) {
      var $el = e.data.el,
        $this = $(this),
        //this is the ul.submenuItems
        $next = $this.next();

      $next.slideToggle();
      $this.parent().toggleClass('open');

      if (!e.data.multiple) {
        //show only one menu at the same time
        //Afficher un seul menu à la fois
        //$el.find('.submenuItems').not($next).slideUp().parent().removeClass('open');
      }
    }

    //SANS ANIMATION
    Accordion.prototype.dropdown2 = function(e) {
      var $el2 = e.data.el2,
        $this = $(this),
        //this is the ul.submenuItems
        $next = $this.next();

      $next.toggle();
      $this.parent().toggleClass('open');
    }

    var accordion = new Accordion($('.accordion-menu'), false);
  })



  function getMenuDeroulant() {
    $('#icon-user-param').w2overlay({
      html: "" +
        "" +
        "<div class='overlay-menu-deroulant' style='width: 200px; font-size: 12px;'>" +

        "<ul class=''>" +
        "<li><a onclick='modifierPassword();'><i class='icon-edit' style='font-size: 19px;'></i> Modifier infos compte</a></li>" +
        "<li><a href='<?php echo $this->url('admin', array('action' => 'logout')); ?>'><i class='icon-off' style='font-size: 19px;'></i> D&eacute;connexion</a></li>" +
        "</ul>" +


        "</div>" +

        "<style> .w2ui-overlay:before{float: left; border: 1px solid rgb(28, 172, 136); top: 2px; border-bottom: 0px solid transparent; border-left:1px solid transparent;}  .w2ui-overlay{float: left; margin-left: 10px; border: 1px solid rgb(28, 172, 136); margin-top: 1 } </style>"




    });
  }
</script>