<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basePath() . '/css/orl/styleUrgence.css'); ?>

<!-- MES JS -->
<?php
echo $this->headScript()->appendFile($this->basePath() . '/js/orl/jsOrl.js');
echo $this->headLink()->appendStylesheet($this->basePath() . '/css/orl/DatePicker.css');
?>

<script>
	//info_bulle();
	//controle_saisie();

	var base_url = window.location.toString();
	var tabUrl = base_url.split("public");
	//POUR LE MENU GAUCHE dans -elementgauche.phtml
	$('#plus_dossier_patient').toggle(true);
	$("#dossier_patient").replaceWith("<li id='dossier_patient' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='" + tabUrl[0] + "public/images_icons/moin-green2.png' alt='Liste' /> Dossier Patient </span></a></li>");
	//dep_dossier_patient1();
	$('#nouveau_style').css({
		'font-weight': 'bold',
		'color': 'white',
		'font-size': '22px'
	});
	//$('#plus_deces').toggle(true);
	//$("#deces").replaceWith("<li id='deces' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> D&eacute;c&egrave;s </span></a></li>");
	//dep_deces1();
	$('#declarer_style').css({
		'font-weight': 'bold',
		'color': 'white',
		'font-size': '22px'
	});
</script>


<script type="text/javascript">
	$(window).load(function() {
		$('#wait').toggle(false);
		$('#contenu').fadeIn().css({
			'visibility': 'visible'
		});

		$('.accordion-menu, .profil-secretariat-menu').toggle(true);
		$('#profil-secretariat-menu-rubrique-dossier-patient  .submenuItems #nouveau-patient-select, #profil-secretariat-menu-rubrique-dossier-patient .submenuItems #nouveau-patient-select > i').css({
			'font-weight': 'bold',
			'color': 'black'
		});

		$('#profil-secretariat-menu-rubrique-dossier-patient div').trigger('dblclick');
	});
</script>

<style>
	#contenu {
		visibility: hidden
	}

	;
</style>



<?php
$form = $this->form;
$form->setAttribute('action', $this->url('secretariat', array('action' => 'enregistrement-patient')));
$form->setAttribute('enctype', 'multipart/form-data');
$this->form->prepare();
echo $this->form()->openTag($form);
?>

<div id="titre" style='font-family: police2; text-decoration: none; color: rgb(24, 153, 121); font-size: 20px; font-weight: bold; padding-left:20px;'>
	<i class="icon-list-alt" style="padding-top: 3px;"></i> &nbsp;
	<span>ETAT CIVIL DU PATIENT</span>
</div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;">
	<span> Chargement ... </span>
</div>
<div id="contenu">

	<div style='width: 100%; height: 100%;'>

		<div class="supprimer_photo" id="div_supprimer_photo" style="position: absolute; left: O; top: 290px;">
			<hass> <input name="supprimer_photo"> </hass>
		</div>

		<div style='width: 15%; height: 150px; float:left;'>
			<div class="photo-patient" id='photo-patient'>
				<input type='file' name="fichier" />
				<!-- RECUPERER L'IMAGE -->
				<input type='hidden' id="fichier_tmp" name="fichier_tmp" />
				<!-- FICHIER TAMPON POUR RECUPERER L'IMAGE DANS LE CONTROLLER -->
			</div>
		</div>



		<div style='width: 80%; height: 150px; float:left;'>
			<table id="form_patient" style="float: left; width: 100%;">

				<tr class="comment-form-patient">
					<td style="width: 33%;" class="wrap-input100">
						<?php echo $this->formRow($this->form->get('SEXE')); ?>
						<span class="symbol-input100">
							<i class="fa fa-venus-mars" aria-hidden="true"></i>
						</span>
					</td>

					<td style="width: 33%;" class="wrap-input100">
						<?php echo $this->formRow($this->form->get('LIEU_NAISSANCE')); ?>
						<span class="symbol-input100">
							<i class="fa fa-info" aria-hidden="true"></i>
						</span>
					</td>

					<td style="width: 33%;" class="wrap-input100">
						<?php echo $this->formRow($this->form->get('EMAIL')); ?>
						<span class="symbol-input100">
							<i class="fa fa-at" aria-hidden="true"></i>
						</span>
					</td>

				</tr>

				<tr class="comment-form-patient">
					<td class="wrap-input100">
						<?php echo $this->formRow($this->form->get('NOM')); ?>
						<span class="symbol-input100">
							<i class="fa fa-user" aria-hidden="true"></i>
						</span>
					</td>
					<td class="wrap-input100">
						<?php echo $this->formRow($this->form->get('TELEPHONE')); ?>
						<span class="symbol-input100">
							<i class="fa fa-phone" aria-hidden="true"></i>
						</span>
					</td>
					<td class="wrap-input100">
						<?php echo $this->formRow($this->form->get('NATIONALITE_ORIGINE')); ?>
						<span class="symbol-input100">
							<i class="fa fa-list" aria-hidden="true"></i>
						</span>
					</td>
				</tr>

				<tr class="comment-form-patient">
					<td class="wrap-input100">
						<?php echo $this->formRow($this->form->get('PRENOM')); ?>
						<span class="symbol-input100">
							<i class="fa fa-user" aria-hidden="true"></i>
						</span>
					</td>
					<td class="wrap-input100">
						<?php echo $this->formRow($this->form->get('PROFESSION')); ?>
						<span class="symbol-input100">
							<i class="fa fa-briefcase" aria-hidden="true"></i>
						</span>
					</td>
					<td class="wrap-input100">
						<?php echo $this->formRow($this->form->get('NATIONALITE_ACTUELLE')); ?>
						<span class="symbol-input100">
							<i class="fa fa-list" aria-hidden="true"></i>
						</span>
					</td>
				</tr>

				<tr class="comment-form-patient">
					<td style="width: 33%;">
						<div class="age" style="float: left; width: 33%;"> <?php echo $this->formRow($this->form->get('AGE')); ?> </div>
						<div class="date_naiss wrap-input100" style="float: left; width: 60%;">
							<?php echo $this->formRow($this->form->get('DATE_NAISSANCE')); ?>
							<span class="symbol-input100">
								<i class="fa fa-calendar" aria-hidden="true"></i>
							</span>
						</div>
					</td>

					<td class="wrap-input100">
						<?php echo $this->formRow($this->form->get('ADRESSE')); ?>
						<span class="symbol-input100">
							<i class="fa fa-home" aria-hidden="true"></i>
						</span>
					</td>
					<td> </td>
				</tr>

			</table>
		</div>

		<div style='width: 3%; height: 150px; float:left;'>

		</div>
	</div>


	<table style="margin-top: -65px; width: 100%; height: 12px;">

		<tr style="">
			<td style="width: 32%;"></td>
			<td style="width: 10%;" id="thoughtbot">
				<button id="annuler" class="btn" style="font-family: police2; font-size: 17px; font-weight: bold; cursor: pointer;">
					Annuler
				</button>
			</td>

			<td style="width: 10%;" id="thoughtbot">
				<button type="submit" name="terminer" id="terminer" class="btn" style=" font-family: police2; font-size: 17px; font-weight: bold; cursor: pointer;">
					Terminer
				</button>
			</td>


			<td style="width: 10%;" id="thoughtbot">
				<button type="submit" name="terminer_admettre" id="terminer_admettre" class="btn" style=" font-family: police2; font-size: 17px; font-weight: bold; cursor: pointer;">
					Terminer et Admettre
				</button>
			</td>

			<td style="width: 10%;" id="thoughtbot">
				<button type="submit" name="terminer_rv" id="terminer_rv" class="btn" style=" font-family: police2; font-size: 17px; font-weight: bold; cursor: pointer;">
					Terminer et Rendez-vous
				</button>
			</td>



			<td style="width: 38%;"></td>

		</tr>
	</table>

</div>

<!-- POP UP pour Confirmation Suppression -->
<div id="confirmation" title="Confirmation de la suppression" style="display: none;">
	<p style="font-size: 16px;">
		<span style="float: left; margin: 0 0px 20px 0;"> <img src="<?php echo $this->basePath() . '/images_icons/warning_16.png'; ?>" />

			Etes-vous s&ucirc;r de vouloir supprimer la photo ?
		</span>
	</p>
</div>


<!-- LES BOUTONS "TERMINER" ou "VALIDER" -->

<?php echo $this->form()->closeTag(); ?>


<script>
	$(document).keypress(function(e) {
		if (e.keyCode == 13) {
			e.preventDefault();
		}
	});
	$('#annuler').click(function() {
		vart = tabUrl[0] + 'public/secretariat/liste-patient';
		$(location).attr("href", vart);
		return false;
	});
</script>