<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basepath() . '/css/hospitalisation/styleListeDemandesExamens.css');
echo $this->headLink()->appendStylesheet($this->basepath() . '/css/facturation/DatePicker.css');
?>
<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basepath() . '/js/facturation/jsListeDemandesVpa.js'); ?>

<?php $form = $this->form; ?>

<style>
	#contenu {
		visibility: hidden
	}
</style>

<script>
	$(window).load(function() {
		$('#wait').toggle(false);
		$('#contenu, #titre').fadeIn().css({
			'visibility': 'visible'
		});

		$('.accordion-menu, .profil-major-menu').toggle(true);
		$('#profil-major-menu-rubrique-vpa  .submenuItems #patientsVpa-effectues-select, #profil-major-menu-rubrique-vpa  .submenuItems #patientsVpa-effectues-select > i').css({
			'font-weight': 'bold',
			'color': 'black'
		});

		$('#profil-major-menu-rubrique-vpa div').trigger('dblclick');

	});
</script>

<div id="titre" style='font-family: police2; text-decoration: none; color: green; font-size: 20px; font-weight: bold; padding-left:20px;'>
	<iS style='font-size: 25px;'>&curren;</iS>
	LISTE DES PATIENTS
</div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;"> <span> Chargement ... </span> </div>
<div id="contenu">

	<table id="patient" class="table table-bordered tab_list_mini">


		<thead id="head" class="head_style">
			<tr>
				<th id="nom_" style='width: 12%;'><input type="text" name="search_browser" value=" Numero dossier" class="search_init" /></th>
				<th id="nom_" style='width: 13%;'><input type="text" name="search_browser" value=" Nom" class="search_init" /></th>
				<th id="prenom_" style='width: 13%;'><input type="text" name="search_browser" value=" Pr&eacute;nom" class="search_init" /></th>
				<th id="date_" style='width: 11%;'><input type="text" name="search_browser" value=" Age" class="search_init" /></th>
				<th id="sexe_" style='width: 9%;'><input type="text" name="search_browser" value=" Sexe" class="search_init" /></th>
				<th id="adresse_" style='width: 17%;'><input type="text" name="search_browser" value=" Adresse" class="search_init" /></th>
				<th id="nationalite_" style='width: 12%;'><input type="text" name="search_browser" value=" M&eacute;decin demandeur" class="search_init" /></th>
				<th id="effectuer">Options</th>
			</tr>
		</thead>


		<tbody id="donnees" class="liste_patient">

			<!-- ************ On affiche les patients en une liste ordonnï¿½e************ -->

		</tbody>


	</table>
</div>


<div id="vue_patient">

</div>

<!--***********************************************************************************************-->

<!--==========================POP UP pour Afficher les détails =================================-->

<!--***********************************************************************************************-->
<div id="envoyer_examen" title="Confirmation de l'envoi des r&eacute;sultats" style="display:none;">

	<p style="font-size: 16px;">
		<span style="float:left; margin:0 0px 20px 0; font-size:17px; ">
			<img src="<?php echo $this->basepath() . '/images_icons/warning_16.png'; ?>" />

			Etes-vous s&ucirc;r de vouloir envoyer les r&eacute;sultats de l'examen ?</span>
	</p>

</div>


<script type="text/javascript">
	$(function() {
		initialisationRecherche();
	});

	$("#vue_patient").toggle(false);
</script>