<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basepath() . '/css/hospitalisation/styleListeDemandesExamens.css');
echo $this->headLink()->appendStylesheet($this->basepath() . '/css/facturation/DatePicker.css');
?>
<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basepath() . '/js/facturation/jsListeDemandesVpa.js');
echo $this->headScript()->appendFile($this->basePath() . '/js/mesjs/bloquerDateOperation.js');
?>
<?php $Control = new \Facturation\View\Helper\DateHelper(); ?>


<!--************************************************************************************************************-->
<!--===================================== BLOCAGE DES JOURS NON CONSULTABLE ====================================-->
<!--===================================== BLOCAGE DES JOURS NON CONSULTABLE ====================================-->
<!--************************************************************************************************************-->
<?php

$today = new \DateTime();
$AnneeActuelle =  $today->format('Y');

/*****Mois 1 *****/
$leMois1 = $today->format('m'); //C'est le mois actuel ï¿½ l'heure du calendrier
$Dimanche1 = $Control->lePremierDimancheDuMois();
/*****Mois 2 *****(Sauf pour le douzieme mois)*/
$leMois2 = $leMois1 + 1;
if ($leMois2 == 13) {
  $leMois2 = 1;
  $AnneeActuelle2 = $AnneeActuelle + 1;
  $AnneeActuelle++;
} else {
  $AnneeActuelle2 = $AnneeActuelle;
}
$Dimanche2 = $Control->lePremierDimancheDuMoisByDate($leMois2, $AnneeActuelle2);
/*****Mois 3 *****/
$leMois3 = $leMois2 + 1;
if ($leMois3 == 13) {
  $leMois3 = 1;
  $AnneeActuelle3 = $AnneeActuelle + 1;
  $AnneeActuelle++;
} else {
  $AnneeActuelle3 = $AnneeActuelle;
}
$Dimanche3 = $Control->lePremierDimancheDuMoisByDate($leMois3, $AnneeActuelle3);
/*****Mois 4 *****/
$leMois4 = $leMois3 + 1;
if ($leMois4 == 13) {
  $leMois4 = 1;
  $AnneeActuelle4 = $AnneeActuelle + 1;
  $AnneeActuelle++;
} else {
  $AnneeActuelle4 = $AnneeActuelle;
}
$Dimanche4 = $Control->lePremierDimancheDuMoisByDate($leMois4, $AnneeActuelle4);
/*****Mois 5 *****/
$leMois5 = $leMois4 + 1;
if ($leMois5 == 13) {
  $leMois5 = 1;
  $AnneeActuelle5 = $AnneeActuelle + 1;
  $AnneeActuelle++;
} else {
  $AnneeActuelle5 = $AnneeActuelle;
}
$Dimanche5 = $Control->lePremierDimancheDuMoisByDate($leMois5, $AnneeActuelle5);
/*****Mois 6 *****/
$leMois6 = $leMois5 + 1;
if ($leMois6 == 13) {
  $leMois6 = 1;
  $AnneeActuelle6 = $AnneeActuelle + 1;
  $AnneeActuelle++;
} else {
  $AnneeActuelle6 = $AnneeActuelle;
}
$Dimanche6 = $Control->lePremierDimancheDuMoisByDate($leMois6, $AnneeActuelle6);
/*****Mois 7 *****/
$leMois7 = $leMois6 + 1;
if ($leMois7 == 13) {
  $leMois7 = 1;
  $AnneeActuelle7 = $AnneeActuelle + 1;
  $AnneeActuelle++;
} else {
  $AnneeActuelle7 = $AnneeActuelle;
}
$Dimanche7 = $Control->lePremierDimancheDuMoisByDate($leMois7, $AnneeActuelle7);
?>


<script>
  //Bloquer les 90 jours non consultable a patir du jour, du mois actuel
  /*****Mois 1*****/
  mois1 = '<?php echo $leMois1 ?>';
  dimanche1 = <?php echo $Dimanche1 ?>;
  annee1 = '<?php echo $today->format('Y'); ?>';


  /*****Mois 2 *****/
  if (<?php echo $leMois2 ?> > 9) {
    mois2 = <?php echo $leMois2 ?>;
  } else {
    mois2 = '0' + '<?php echo $leMois2 ?>';
  }
  dimanche2 = <?php echo $Dimanche2 ?>;
  annee2 = '<?php echo $AnneeActuelle2 ?>';


  /*****Mois 3 *****/
  if (<?php echo $leMois3 ?> > 9) {
    mois3 = <?php echo $leMois3 ?>;
  } else {
    mois3 = '0' + '<?php echo $leMois3 ?>';
  }
  dimanche3 = <?php echo $Dimanche3 ?>;
  annee3 = '<?php echo $AnneeActuelle3 ?>';


  /*****Mois 4 *****/
  if (<?php echo $leMois4 ?> > 9) {
    mois4 = <?php echo $leMois4 ?>;
  } else {
    mois4 = '0' + '<?php echo $leMois4 ?>';
  }
  dimanche4 = <?php echo $Dimanche4 ?>;
  annee4 = '<?php echo $AnneeActuelle4 ?>';

  /*****Mois 5 *****/
  if (<?php echo $leMois5 ?> > 9) {
    mois5 = <?php echo $leMois5 ?>;
  } else {
    mois5 = '0' + '<?php echo $leMois5 ?>';
  }
  dimanche5 = <?php echo $Dimanche5 ?>;
  annee5 = '<?php echo $AnneeActuelle5 ?>';

  /*****Mois 6 *****/
  if (<?php echo $leMois6 ?> > 9) {
    mois6 = <?php echo $leMois6 ?>;
  } else {
    mois6 = '0' + '<?php echo $leMois6 ?>';
  }
  dimanche6 = <?php echo $Dimanche6 ?>;
  annee6 = '<?php echo $AnneeActuelle6 ?>';

  /*****Mois 7 *****/
  if (<?php echo $leMois7 ?> > 9) {
    mois7 = <?php echo $leMois7 ?>;
  } else {
    mois7 = '0' + '<?php echo $leMois7 ?>';
  }
  dimanche7 = <?php echo $Dimanche7 ?>;
  annee7 = '<?php echo $AnneeActuelle7 ?>';
  /****************************
   *===========================
   **************************/
  //bloquerDateOperation();
  /**************************
   * ========================
   **************************/

  /*<!--************************************************************************************************************-->
    <!--===================================== FIN BLOCAGE DES JOURS NON CONSULTABLE ================================-->
    <!--===================================== FIN BLOCAGE DES JOURS NON CONSULTABLE ================================-->
    <!--************************************************************************************************************--*/
</script>


<?php $form = $this->form; ?>

<style>
  #contenu {
    visibility: hidden
  }
</style>

<script>
  $(window).load(function() {
    $('#wait').toggle(false);
    $('#contenu, #titre').fadeIn().css({
      'visibility': 'visible'
    });

    $('.accordion-menu, .profil-major-menu').toggle(true);
    $('#profil-major-menu-rubrique-vpa  .submenuItems #vpa-encours-select, #profil-major-menu-rubrique-vpa  .submenuItems #vpa-encours-select > i').css({
      'font-weight': 'bold',
      'color': 'black'
    });

    $('#profil-major-menu-rubrique-vpa div').trigger('dblclick');

  });
</script>

<div id="titre" style='font-family: police2; text-decoration: none; color: green; font-size: 20px; font-weight: bold; padding-left:20px;'>
  <iS style='font-size: 25px;'>&curren;</iS>
  LISTE DES PATIENTS
</div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;"> <span> Chargement ... </span> </div>
<div id="contenu">

  <table id="patient" class="table table-bordered tab_list_mini">


    <thead id="head" class="head_style">
      <tr>
        <th id="nom_" style='width: 12%;'><input type="text" name="search_browser" value=" Numero dossier" class="search_init" /></th>
        <th id="nom_" style='width: 13%;'><input type="text" name="search_browser" value=" Nom" class="search_init" /></th>
        <th id="prenom_" style='width: 13%;'><input type="text" name="search_browser" value=" Pr&eacute;nom" class="search_init" /></th>
        <th id="date_" style='width: 11%;'><input type="text" name="search_browser" value=" Age" class="search_init" /></th>
        <th id="sexe_" style='width: 9%;'><input type="text" name="search_browser" value=" Sexe" class="search_init" /></th>
        <th id="adresse_" style='width: 17%;'><input type="text" name="search_browser" value=" Adresse" class="search_init" /></th>
        <th id="nationalite_" style='width: 12%;'><input type="text" name="search_browser" value=" M&eacute;decin demandeur" class="search_init" /></th>
        <th id="effectuer">Options</th>
      </tr>
    </thead>


    <tbody id="donnees" class="liste_patient">

      <!-- ************ On affiche les patients en une liste ordonnï¿½e************ -->

    </tbody>


  </table>
</div>


<div id="vue_patient">

</div>

<!--***********************************************************************************************-->

<!--==========================POP UP pour Afficher les détails =================================-->

<!--***********************************************************************************************-->
<div id="envoyer_examen" title="Confirmation de l'envoi des r&eacute;sultats" style="display:none;">

  <p style="font-size: 16px;">
    <span style="float:left; margin:0 0px 20px 0; font-size:17px; ">
      <img src="<?php echo $this->basepath() . '/images_icons/warning_16.png'; ?>" />

      Etes-vous s&ucirc;r de vouloir envoyer les r&eacute;sultats de l'examen ?</span>
  </p>

</div>


<script type="text/javascript">
  $(function() {
    initialisation();
  });

  $("#vue_patient").toggle(false);
</script>