<!-- MES STYLES --> 
<?php echo $this->headLink()->appendStylesheet($this->basepath().'/css/hospitalisation/styleListeDemandesExamens.css');
      echo $this->headLink()->appendStylesheet($this->basepath().'/css/facturation/DatePicker.css'); 
?>
<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basepath().'/js/facturation/jsListeDemandesVpa.js');?>

<?php $form = $this->form; ?>

<style>
#contenu{ visibility: hidden }
</style>

<script>
var base_url = window.location.toString();
var tabUrl = base_url.split("public");
/***POUR LE MENU GAUCHE dans -elementgauche.phtml***/
$('#plus_operationVpa').toggle(true); 
$("#operationVpa").replaceWith("<li id='operationVpa' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moins-vert.PNG' alt='Liste' /> Demandes de VPA </span></a></li>");
depVpa3();
$('#recherche_styleVpa').css({'font-weight':'bold','color':'white','font-size':'21px'});


$(window).load(function () {
	$('#wait').toggle(false);
	$('#contenu').fadeIn().css({'visibility':'visible'});
});
</script>

<div id="titre" style='font-family: police2; text-decoration: none; color: green; font-size: 20px; font-weight: bold; padding-left:20px;'>
	<iS style='font-size: 25px;'>&curren;</iS>
	LISTE DES PATIENTS
</div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>
<div id="contenu"> 

            <table id="patient" class="table table-bordered tab_list_mini" >
            
            
       <thead id="head" class="head_style">
			<tr>
			    <th id="nom_" style='width: 12%;'><input type="text"
					name="search_browser" value=" Numero dossier" class="search_init" /></th>
				<th id="nom_" style='width: 13%;'><input type="text"
					name="search_browser" value=" Nom" class="search_init" /></th>
				<th id="prenom_" style='width: 13%;'><input type="text"
					name="search_browser" value=" Pr&eacute;nom" class="search_init" /></th>
				<th id="date_" style='width: 11%;'><input type="text"
					name="search_browser" value=" Age" class="search_init" /></th>
				<th id="sexe_" style='width: 9%;'><input type="text"
					name="search_browser" value=" Sexe" class="search_init" /></th>
				<th id="adresse_" style='width: 17%;'><input type="text"
					name="search_browser" value=" Adresse" class="search_init" /></th>
				<th id="nationalite_" style='width: 12%;'><input type="text"
					name="search_browser" value=" M&eacute;decin demandeur" class="search_init" /></th>
				<th id="effectuer">Options</th>			
				</tr>
		</thead>


				<tbody id="donnees" class="liste_patient">

					<!-- ************ On affiche les patients en une liste ordonnï¿½e************ -->

				</tbody>


			</table>
</div>


<div id="vue_patient">

</div>
        
<!--***********************************************************************************************-->                              

<!--==========================POP UP pour Afficher les détails =================================-->                              
                          
<!--***********************************************************************************************-->  
        <div id="envoyer_examen" title="Confirmation de l'envoi des r&eacute;sultats" style="display:none;">
             
              <p style="font-size: 16px;">
                 <span style="float:left; margin:0 0px 20px 0; font-size:17px; ">
                 <img src="<?php echo $this->basepath().'/images_icons/warning_16.png';?>" />
                                
                 Etes-vous s&ucirc;r de vouloir envoyer les r&eacute;sultats de l'examen ?</span>
             </p>
             
        </div>
        
        
<script type="text/javascript">
$(function(){
	initialisationRecherche();
});

$("#vue_patient").toggle(false);
</script>